% This simulation is based on Hasti's simulation parameters
% use exact parameters and setup.
run("../MultiOb/SimTunableMultiOb256Setup.m");
matFile = CIRLDataPath + "/Simulation/Tunable/SimTunableMultiOb256SNR3.mat";

%% run RunReconstruction
wD     = 0.09;
cutoff = -1;
A      = -1;
sigma  = -1;
radius = round(uc*X*dXY);
Filter = bead(dXY, dXY, X, Z, radius*dXY, radius*dXY);
RunReconstruction(...
            'savemat',          1, ...
            'u',                u, ...
            'uc',               uc, ...
            'X' ,               X , ...
            'Y' ,               Y , ...
            'Z' ,               Z , ...
            'Nphi',             length(phi), ...
            'Nthe',             length(theta), ...
            'phi',              phi, ...
            'theta',            theta, ...
            'w',                w, ...
            'dXY',              dXY, ...
            'dZ',               dZ, ...
            'psfParam',         psfpar, ...
            'reconVars',        {"wD"}, ...
            'reconVals',        {wD}, ...
            'dataFile',         matFile, ...
            'psfFunction',      @PSFAgard, ...
            'psfArgs',          {"X", "Z", "dXY", "dZ"}, ...
            'patternFunction',  @PatternTunable3D3Slits, ...
            'patternArgs',      {"X", "Y", "Z", "u", "w", "dXY", "dZ", "phi", "offs", "theta", phizDeg},...
            'reconFunction',    @GWFTunable3D, ...
            'reconArgs',        {"g", "h", "im", "uc", "u", "phi", "offs", "theta", "wD", "dXY", "dZ", cutoff, A, sigma, 1, Filter},...
...            'reconFunction',    @Reconstruction_GUS_Tunable_3DRec, ...
...            'reconArgs',        {"g", "h", im(:,:,:,1,1,2), "uc", u(1), "phi", "theta", "wD", "wD", 1, "dXY", "dZ", 1, 1.7, 20},...
            ...
            'reportFolder',     CIRLReportPath,...
            'reportFile',       "SimTunableGWFMultiOb256SNR4.tex")
