function [ g, G ] = FreqForwardModel( Ob, h, Pattern_Axial, Phase, um, dXY )
[Y, X, Z] = size(Ob);
NPhase = length(Phase);
h1     = h.*Pattern_Axial;
H0     = FT(h);
H1     = FT(h1);
H      = cat(5, H0, H1, H1);
M      = PhaseMatrix(Phase);
ObMat  = repmat(Ob, 1, 1, 1, 1, NPhase);
[yy, xx, zz] = meshgrid(0 : 1 : Y-1, 0 : 1 : X-1, 0 : 1 : Z-1);
fxx    = um*xx*dXY;   % 2fx abscissae
fyy    = um*yy*dXY;   % 2fx abscissae
ObMat(:,:,:,:,1) = FT(ObMat(:,:,:,:,1));
ObMat(:,:,:,:,2) = FT(ObMat(:,:,:,:,2).*exp(-1i*2*pi*fyy));
ObMat(:,:,:,:,3) = FT(ObMat(:,:,:,:,3).*exp(+1i*2*pi*fyy));
G      = reshape(reshape(ObMat.*H, X*Y*Z, 3)*M', Y, X, Z, 1, 3);
g(:,:,:,:,1) = abs(IFT(G(:,:,:,:,1)));
g(:,:,:,:,2) = abs(IFT(G(:,:,:,:,2)));
g(:,:,:,:,3) = abs(IFT(G(:,:,:,:,3)));
