% use exact parameters and setup.
run("../StarCorner/Sim3WStarCorner100Setup.m");
matFile = CIRLDataPath + "/Simulation/3W/Sim3WStarCorner100.mat";

%% run RunReconstruction
wD     = 1e-6;
cutoff = -1;
A      = -1;
sigma  = sqrt(0.5);
RunReconstruction(...
            'savemat',          1, ...
            'obScale',          obScale, ...
            'u',                u, ...
            'uc',               uc, ...
            'X' ,               X , ...
            'Y' ,               Y , ...
            'Z' ,               Z , ...
            'Nphi',             length(phi), ...
            'Nthe',             length(theta), ...
            'phi',              phi, ...
            'theta',            theta, ...
            'w',                w, ...
            'dXY',              dXY, ...
            'dZ',               dZ, ...
            'psfParam',         psfpar, ...
            'reconVars',        {"wD"}, ...
            'reconVals',        {wD}, ...
            'dataFile',         matFile, ...
            'psfFunction',      @PSFLutz, ...
            'psfArgs',          {"X", "Z", "dXY", "dZ", "psfParam"}, ...
            'patternFunction',  @Pattern3W3D, ...
            'patternArgs',      {"X", "Y", "Z", "u", "w", "dXY", "dZ", "phi", "offs", "theta", phizDeg},...
            'reconFunction',    @GWF3W3D, ...
            'reconArgs',        {"g", "h", "im", "uc", "u", "phi", "offs", "theta", "wD", "dXY", "dZ", cutoff, A, sigma},...
            ...
            'reportFolder',     CIRLReportPath,...
            'reportFile',       "")