run("../../Bead/SimTunableOffFreqBead100Setup.m");
matFile = CIRLDataPath + "/Simulation/Tunable/SimTunableOffFreqBead100.mat";

%% run RunReconstruction
numIt = 200;
picIn = 5;    % picture every 5 interations

% perturbate the frequency by 2%
u(1) = u(1) + 0.01*u(1)
u(2) = u(2) - 0.01*u(2)
u(3) = u(3) + 0.01*u(3)
%u   = u + 0.01*u
%u    = u + 0.001*u
phi = [-10 130 230]
%phi = [2.4677 118.3986 241.4528]

RunReconstruction(...
            'savemat',          1, ...
            'u',                u, ...
            'uc',               uc, ...
            'X' ,               X , ...
            'Y' ,               Y , ...
            'Z' ,               Z , ...
            'Nphi',             length(phi), ...
            'Nthe',             length(theta), ...
            'phi',              phi, ...
            'theta',            theta, ...
            'w',                w, ...
            'dXY',              dXY, ...
            'dZ',               dZ, ...
            'psfParam',         psfpar, ...
            'reconVars',        {"numIt"}, ...
            'reconVals',        {numIt}, ...
            'dataFile',         matFile, ...
            'psfFunction',      @PSFAgard, ...
            'psfArgs',          {"X", "Z", "dXY", "dZ"}, ...
            'reconFunction',    @HotOneShotLBFGSBNoDouble, ...
            'reconArgs',        {@HotForwardModel, ...
                                 @HotGradient, ...
                                 @HotStepSize, ...
                                 @UpSampling, ...
                                 @imTunable,...
                                 @jmTunable,...
                                 "g", "h", "dXY", "dZ", 2, "u", "w", "theta", "phi", offs, phizDeg,...
                                 "numIt", 5e-20 ,-1, -1, picIn},...
            ...
            'reportFolder',     CIRLReportPath,...
            'reportFile',       "SimTunableHotOffFreqLBFGSBOffFreqBead100Iter10NoDouble.tex")
