run("../../OSSRMultiOb/Sim3WOSSRMultiOb256Setup.m");
load(CIRLDataPath + "/Simulation/3W/Sim3WOSSRMultiOb256.mat", 'g');

%% Wiener parameter
wD = 0.01;

% lateral fractions
qn = [0, 1, -1, 2, -2]/2; % qn = (1:Nphi) - (Nphi+1)/2;

% decomposition matrix coefficients
cn = [1, 2/3, 2/3, 1/3, 1/3];

% input OTFs
load(CIRLDataPath + "/Simulation/SimOTFs/OTFs_256_256_256.mat", 'Hn');

%% run reconstruction
reconOb = OTFGWFCore(    g,  ...
                         Hn, ...
                         qn, ...
                         cn, ...
                         uc, ...
                         u, ...
                         phi, ...
                         offs, ...
                         theta, ...
                         wD, ...
                         dXY, dZ);

save('Sim3WOTF256GWFOSSRMultiOb256');